
TG_API_KEY = 'xxxxxxxxx:IL-MIO-TOKEN-PER-IL-BOT-TELEGRAM'

LUIS_APP_ID = 'IL-MIO-UUID-PER-L-ISTANZA-DI-LUIS'
LUIS_START_KEY = 'IL-MIO-TOKEN-PER-L-ISTANZA-DI-LUIS'
LUIS_START_URL = 'https://westus.api.cognitive.microsoft.com/luis/v2.0/apps/'

PRETTY_OUTPUT = True
